version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: supermike2020/python-blog-app
    docker:
      - image: cimg/base:2022.03
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - aws-cli/setup
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to ECR
          command: |
            docker login -u AWS -p $(aws ecr get-login-password --region us-east-2) ${ECR_URI}
            docker tag $IMAGE_NAME:latest ${ECR_URI}:latest
            #aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_URI}
            docker push ${ECR_URI}:latest 
            #echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            #docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - main
                - dev
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: 
                - main
                - dev
